# Generated by Django 2.2.5 on 2020-02-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule_interview',
            name='candidate_name',
        ),
        migrations.AddField(
            model_name='schedule_interview',
            name='employee',
            field=models.ManyToManyField(to='interview.Employee'),
        ),
    ]
